version: '3'

services:
  db:
    image: postgres:13
    container_name: postgres_db_node_bz
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydb
    ports:
      - "5234:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  node:
    image: ${DOCKER_USERNAME}/nodejs_postgres_bz:latest
    container_name: nodejs_app_bz
    depends_on:
      - db
    ports:
      - "3754:3000"
    environment:
      - DATABASE_URL=postgres://postgres:mysecretpassword@db:5432/mydb
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    restart: unless-stopped
    command: ["npm", "run","start"]


volumes:
  db_data:
